//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace RecallFoodAlert.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RecallEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RecallEntities object using the connection string found in the 'RecallEntities' section of the application configuration file.
        /// </summary>
        public RecallEntities() : base("name=RecallEntities", "RecallEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecallEntities object.
        /// </summary>
        public RecallEntities(string connectionString) : base(connectionString, "RecallEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecallEntities object.
        /// </summary>
        public RecallEntities(EntityConnection connection) : base(connection, "RecallEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TextAlert> TextAlert
        {
            get
            {
                if ((_TextAlert == null))
                {
                    _TextAlert = base.CreateObjectSet<TextAlert>("TextAlert");
                }
                return _TextAlert;
            }
        }
        private ObjectSet<TextAlert> _TextAlert;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TextAlert EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTextAlert(TextAlert textAlert)
        {
            base.AddObject("TextAlert", textAlert);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EccoSelect.com", Name="TextAlert")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TextAlert : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TextAlert object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="mobilePhone">Initial value of the MobilePhone property.</param>
        /// <param name="alertType">Initial value of the AlertType property.</param>
        /// <param name="registrationDateTime">Initial value of the RegistrationDateTime property.</param>
        public static TextAlert CreateTextAlert(global::System.Int32 id, global::System.String mobilePhone, global::System.String alertType, global::System.DateTime registrationDateTime)
        {
            TextAlert textAlert = new TextAlert();
            textAlert.Id = id;
            textAlert.MobilePhone = mobilePhone;
            textAlert.AlertType = alertType;
            textAlert.RegistrationDateTime = registrationDateTime;
            return textAlert;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MobilePhone
        {
            get
            {
                return _MobilePhone;
            }
            set
            {
                OnMobilePhoneChanging(value);
                ReportPropertyChanging("MobilePhone");
                _MobilePhone = StructuralObject.SetValidValue(value, false, "MobilePhone");
                ReportPropertyChanged("MobilePhone");
                OnMobilePhoneChanged();
            }
        }
        private global::System.String _MobilePhone;
        partial void OnMobilePhoneChanging(global::System.String value);
        partial void OnMobilePhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AlertType
        {
            get
            {
                return _AlertType;
            }
            set
            {
                OnAlertTypeChanging(value);
                ReportPropertyChanging("AlertType");
                _AlertType = StructuralObject.SetValidValue(value, false, "AlertType");
                ReportPropertyChanged("AlertType");
                OnAlertTypeChanged();
            }
        }
        private global::System.String _AlertType;
        partial void OnAlertTypeChanging(global::System.String value);
        partial void OnAlertTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateCode
        {
            get
            {
                return _StateCode;
            }
            set
            {
                OnStateCodeChanging(value);
                ReportPropertyChanging("StateCode");
                _StateCode = StructuralObject.SetValidValue(value, true, "StateCode");
                ReportPropertyChanged("StateCode");
                OnStateCodeChanged();
            }
        }
        private global::System.String _StateCode;
        partial void OnStateCodeChanging(global::System.String value);
        partial void OnStateCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegistrationDateTime
        {
            get
            {
                return _RegistrationDateTime;
            }
            set
            {
                OnRegistrationDateTimeChanging(value);
                ReportPropertyChanging("RegistrationDateTime");
                _RegistrationDateTime = StructuralObject.SetValidValue(value, "RegistrationDateTime");
                ReportPropertyChanged("RegistrationDateTime");
                OnRegistrationDateTimeChanged();
            }
        }
        private global::System.DateTime _RegistrationDateTime;
        partial void OnRegistrationDateTimeChanging(global::System.DateTime value);
        partial void OnRegistrationDateTimeChanged();

        #endregion

    }

    #endregion

}
