//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecallFoodAlert.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextAlert
    {
        public int Id { get; set; }
        public string MobilePhone { get; set; }
        public string AlertType { get; set; }
        public string StateCode { get; set; }
        public System.DateTime RegistrationDateTime { get; set; }
    }
}
